### ISSUE TITLE
test: zlib-binding.deflate flaky

### ISSUE THREAD

**Issue by fhinkel** [v8/node#45]
The `async-hooks/test-zlib.zlib-binding.deflate.js` test is flaky since we updated Node to Node master yesterday. Any async hooks folks want to look into this cc @addaleax @trevnorris? @Trott is seeing a `corrupted double-linked list` error with the same test (on Node master with his PR [#17856](https://github.com/nodejs/node/pull/17856#issuecomment-354517326)). 

```not ok 56 async-hooks/test-zlib.zlib-binding.deflate
  ---
  duration_ms: 0.264
  severity: fail
  stack: |-
    *** Error in `out/Release/node': malloc(): smallbin double linked list corrupted: 0x0000000002b8e990 ***
```

This is the builder: https://ci.chromium.org/p/v8/builders/luci.v8.try/v8_node_linux64_rel
Here's one of the builds with a malloc error: https://ci.chromium.org/p/v8/builds/b8957891491866158528

**Comment by Trott** [comment]
One of the things I've noticed on the other PR is that it's only flaky on the Rackspace hosts and not the Softlayer hosts. I think the only real difference is our Rackspace hosts have less memory and less CPU, but @nodejs/build could confirm.

@addaleax suggested that it might would be helpful to log into a machine where its failing and run the test under valgrind.

**Comment by joyeecheung** [comment]
FWIW I have seen it on Windows with vs2017 before, but it disappeared when I ran it using the stress-test job, and it disappeared on the full CI after a rebase: https://github.com/nodejs/node/pull/17338#issuecomment-352725302

**Comment by addaleax** [comment]
Yeah, without a reproduction I’d still say that trying to get something from valgrind or a similar tool would be best…

**Comment by targos** [comment]
Got a stack trace in canary:

```
not ok 54 async-hooks/test-zlib.zlib-binding.deflate
  ---
  duration_ms: 0.169
  severity: fail
  stack: |-
    *** Error in `out/Release/node': malloc(): smallbin double linked list corrupted: 0x0000000091e23ba0 ***
    ======= Backtrace: =========
    /lib64/libc.so.6(+0x8c9d2)[0x3ff8490c9d2]
    /lib64/libc.so.6(+0x903b0)[0x3ff849103b0]
    /lib64/libc.so.6(__libc_malloc+0x70)[0x3ff84912850]
    /lib64/libstdc++.so.6(_Znwm+0x22)[0x3ff84d063e2]
    out/Release/node(_ZNSt6vectorIhSaIhEE19_M_emplace_back_auxIIRKhEEEvDpOT_+0x4c)[0x80e414a4]
    out/Release/node(_ZN2v88internal26SourcePositionTableBuilder8AddEntryERKNS0_18PositionTableEntryE+0x142)[0x80e662b2]
    out/Release/node(_ZN2v88internal26SourcePositionTableBuilder11AddPositionEmNS0_14SourcePositionEb+0x32)[0x80e662fa]
    out/Release/node(_ZN2v88internal11interpreter19BytecodeArrayWriter5WriteEPNS1_12BytecodeNodeE+0xc2)[0x80baa37a]
    out/Release/node(_ZN2v88internal11interpreter20BytecodeArrayBuilder10StackCheckEi+0x9e)[0x80ba3ede]
    out/Release/node(_ZN2v88internal11interpreter17BytecodeGenerator20GenerateBytecodeBodyEv+0x1da)[0x80bbd3fa]
    out/Release/node(_ZN2v88internal11interpreter17BytecodeGenerator16GenerateBytecodeEm+0x2dc)[0x80bbd89c]
    out/Release/node(_ZN2v88internal11interpreter25InterpreterCompilationJob14ExecuteJobImplEv+0x1b8)[0x80bcc610]
    out/Release/node[0x80a11e5c]
    out/Release/node[0x80a14228]
    out/Release/node(_ZN2v88internal8Compiler7CompileENS0_6HandleINS0_18SharedFunctionInfoEEENS1_18ClearExceptionFlagE+0x4d4)[0x80a1818c]
    out/Release/node(_ZN2v88internal8Compiler7CompileENS0_6HandleINS0_10JSFunctionEEENS1_18ClearExceptionFlagE+0x232)[0x80a1a1ba]
    out/Release/node(_ZN2v88internal19Runtime_CompileLazyEiPPNS0_6ObjectEPNS0_7IsolateE+0x98)[0x80da22e0]
    [0x9c68904474]
```

https://ci.nodejs.org/job/node-test-commit-node-v8/278/

**Comment by Trott** [comment]
It appears that https://github.com/nodejs/node/pull/18241 may have fixed this. (Or maybe something else fixed it? Point is, I don't think I'm seeing it anymore!)

**Comment by hashseed** [comment]
I just sync'ed vee-eight-lkgr with upstream master. I'll consider this fixed. Thanks!
